server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
    driver-class-name: @datasource.driver@
  liquibase:
    change-log: @liquibase.changelog@
    url: @liquibase.url@
    user: @liquibase.user@
    password: @liquibase.password@
    contexts: @liquibase.contexts@
  mail:
    host: smtp.gmail.com
    port: 587
    username: easy.food.service19@gmail.com
    password: MK4vaJ73
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  messages:
    basename: i18n/messages
#  jpa:
#    show-sql: true

app:
  name: easyOrder
  frontend-url: "http://localhost:8080"
  image-path: /images
  mail:
    from: "EasyFood <easy.food.service19@gmail.com>"

jwt:
  token:
    secret:
      base64: J6hiak8YjLhMYb6/J5CWAxnkHErQa69NCh2A7VxCF2QizMJX8WnskeSkXLEIM20zFsHBrS+7N63fKxnArw8jfeLh10aGh1vJt25Y5FxFRL2nc5Hdb+JQ6LGZUVFqO1r5APwPzM0cQ52ulRXILmMGnHopIsLuUWK9DF7evGka0rU=
      default:
    expire-length:
      default: 7200
      remember-me: 1296000