server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024

spring:
  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
    driver-class-name: @datasource.driver@
  liquibase:
    change-log: @liquibase.changelog@
    url: @liquibase.url@
    user: @liquibase.user@
    password: @liquibase.password@
    contexts: @liquibase.contexts@
  mail:
    host: localhost
    port: 25
    username:
    password:


app:
  name: easyOrder
  frontend-url: @frontend.url@
  mail:
    base-url: http://localhost:${server.port}
    from: easy-order@localhost

jwt:
  token:
    secret:
      base64: J6hiak8YjLhMYb6/J5CWAxnkHErQa69NCh2A7VxCF2QizMJX8WnskeSkXLEIM20zFsHBrS+7N63fKxnArw8jfeLh10aGh1vJt25Y5FxFRL2nc5Hdb+JQ6LGZUVFqO1r5APwPzM0cQ52ulRXILmMGnHopIsLuUWK9DF7evGka0rU=
      default:
    expire-length:
      default: 7200
      remember-me: 1296000

debug: true